/*
 * universal search engine
 * universal search engine api
 *
 * OpenAPI spec version: 2.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.UniversalSearchEngine) {
      root.UniversalSearchEngine = {};
    }
    root.UniversalSearchEngine.Object1 = factory(root.UniversalSearchEngine.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The Object1 model module.
   * @module model/Object1
   * @version 2.0.1
   */

  /**
   * Constructs a new <code>Object1</code>.
   * @alias module:model/Object1
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Object1</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Object1} obj Optional instance to populate.
   * @return {module:model/Object1} The populated <code>Object1</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('objectClickedOn'))
        obj.objectClickedOn = ApiClient.convertToType(data['objectClickedOn'], 'String');
      if (data.hasOwnProperty('clickedByUser'))
        obj.clickedByUser = ApiClient.convertToType(data['clickedByUser'], 'String');
    }
    return obj;
  }

  /**
   * This will be the object id of the clicked object
   * @member {String} objectClickedOn
   */
  exports.prototype.objectClickedOn = undefined;

  /**
   * This will be id of the user who clicked the object
   * @member {String} clickedByUser
   */
  exports.prototype.clickedByUser = undefined;


  return exports;

}));
