/*
 * universal search engine
 * universal search engine api
 *
 * OpenAPI spec version: 1.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UniversalSearchEngine);
  }
}(this, function(expect, UniversalSearchEngine) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ModelObject', function() {
      beforeEach(function() {
        instance = new UniversalSearchEngine.ModelObject();
      });

      it('should create an instance of ModelObject', function() {
        // TODO: update the code to test ModelObject
        expect(instance).to.be.a(UniversalSearchEngine.ModelObject);
      });

      it('should have the property obejctID (base name: "obejctID")', function() {
        // TODO: update the code to test the property obejctID
        expect(instance).to.have.property('obejctID');
        // expect(instance.obejctID).to.be(expectedValueLiteral);
      });

    });
  });

}));
