/*
 * universal search engine
 * universal search engine api
 *
 * OpenAPI spec version: 1.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UniversalSearchEngine);
  }
}(this, function(expect, UniversalSearchEngine) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Object1', function() {
      beforeEach(function() {
        instance = new UniversalSearchEngine.Object1();
      });

      it('should create an instance of Object1', function() {
        // TODO: update the code to test Object1
        expect(instance).to.be.a(UniversalSearchEngine.Object1);
      });

      it('should have the property objectClickedOn (base name: "objectClickedOn")', function() {
        // TODO: update the code to test the property objectClickedOn
        expect(instance).to.have.property('objectClickedOn');
        // expect(instance.objectClickedOn).to.be(expectedValueLiteral);
      });

      it('should have the property clickedByUser (base name: "clickedByUser")', function() {
        // TODO: update the code to test the property clickedByUser
        expect(instance).to.have.property('clickedByUser');
        // expect(instance.clickedByUser).to.be(expectedValueLiteral);
      });

    });
  });

}));
